<a href="https://colab.research.google.com/github/Himangi-77/Python_codes/blob/main/TSNE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import seaborn as sns
from sklearn.manifold import TSNE
from bioinfokit.visuz import cluster
import numpy as np

In [4]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
x = iris.iloc[:,0:4]
y = iris.iloc[:,4]

In [9]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [10]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [19]:
data_tsne = TSNE(n_components = 3).fit_transform(x)
color_class = y.to_numpy()
cluster.tsneplot(score=data_tsne,colorlist=color_class,legendpos='upper right',legendanchor=(1.15,1))

/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:783: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:793: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  FutureWarning,
WARNING:matplotlib.font_manager:findfont: Font family ['Arial'] not found. Falling back to DejaVu Sans.

In [20]:
data_tsne

array([[ 132.70256   ,   69.23899   ,   64.38353   ],
       [  81.59117   ,  -94.578636  ,   31.871107  ],
       [  66.030525  ,  -59.29486   ,   52.423332  ],
       [  29.189135  , -122.23136   ,   88.573     ],
       [ -56.438263  ,  -79.52125   ,   95.94593   ],
       [ -37.075996  ,   19.907557  ,  128.09047   ],
       [  -3.4994826 ,  -87.42786   ,   35.302895  ],
       [ -85.353676  ,  -87.28781   ,   59.809692  ],
       [  39.202038  , -138.68558   ,    7.877311  ],
       [ -98.143166  ,  -65.680626  ,    2.3605108 ],
       [ -75.21069   ,   30.499424  ,   98.29898   ],
       [ 143.06377   ,   90.070656  ,   12.918069  ],
       [  67.88124   ,  -91.67603   ,   85.61212   ],
       [  38.39178   , -168.78386   ,   40.82872   ],
       [ -76.86549   ,  -27.5808    ,  177.42691   ],
       [-116.28416   ,  -14.20218   ,  146.7464    ],
       [ -76.838196  ,  -53.354317  ,  139.38353   ],
       [ -85.93442   ,  -45.392834  ,   55.51359   ],
       [ -32.713417  ,   -9.537931  ,  162.5557    ],
       [ 157.93546   ,  -13.434892  ,   10.722248  ],
       [ -37.722027  ,   13.3590145 ,   72.82967   ],
       [ -37.546337  ,  -40.068195  ,  113.082535  ],
       [ -22.078835  , -118.57745   ,   88.34685   ],
       [ -60.729973  ,  -14.037745  ,   26.40408   ],
       [ -47.612366  , -147.60617   ,    8.1570425 ],
       [-117.7493    , -101.16657   ,   23.41161   ],
       [ -48.53493   ,  -66.563705  ,   12.553179  ],
       [ -57.195686  ,  -26.587637  ,   78.13681   ],
       [ -25.485327  ,  -31.54427   ,   48.59453   ],
       [  -9.522054  , -115.43533   ,   -2.7023523 ],
       [  25.073612  ,  147.23476   ,   23.34175   ],
       [   1.8814499 ,  -16.112566  ,  118.92424   ],
       [ -75.07941   ,   -9.493443  ,  122.89381   ],
       [ -81.14105   ,   17.056252  ,  157.87541   ],
       [-106.83442   ,  -24.273336  ,   12.291786  ],
       [  28.152912  ,  -53.58827   ,   67.97704   ],
       [-109.0195    ,  -57.885227  ,  101.9254    ],
       [ -42.057457  ,  -69.82145   ,   58.437866  ],
       [  64.50494   , -135.66156   ,   55.148254  ],
       [ -54.298874  , -108.4444    ,   42.956528  ],
       [ -10.290962  ,  -68.219986  ,   86.95017   ],
       [  87.81743   , -139.86017   ,    5.659916  ],
       [  34.75046   , -102.39541   ,   50.264065  ],
       [ -68.02301   , -103.25246   ,  -10.846997  ],
       [ -19.66775   ,  -68.89672   ,  147.6488    ],
       [  39.909172  ,  -92.32177   ,    6.2604527 ],
       [-102.88108   ,   -6.3978963 ,   84.29162   ],
       [   3.4242516 , -131.5913    ,   42.965324  ],
       [ 168.5956    ,   29.331066  ,  -19.318043  ],
       [   6.70797   ,  -18.61078   ,   71.14913   ],
       [ -22.206717  ,   48.134823  ,    6.614329  ],
       [  67.18725   ,  -45.58165   ,  -15.089645  ],
       [  41.870564  ,   52.15681   ,  -86.16208   ],
       [  43.985073  ,   34.773808  ,   95.42815   ],
       [  44.4698    ,  -58.04017   , -101.48147   ],
       [  73.87954   ,   59.779087  ,  -14.839167  ],
       [  69.779434  ,  -78.15334   ,  -67.203415  ],
       [  79.41049   ,  121.02816   ,   86.22746   ],
       [  93.977295  ,  -25.534012  ,  -53.96355   ],
       [  75.94617   ,   18.7054    ,   63.87605   ],
       [  98.28677   ,   15.421829  ,  109.04745   ],
       [  51.7904    ,   24.171534  ,    0.93428755],
       [  39.96724   ,   78.318016  ,  123.45164   ],
       [  13.978295  ,  -63.132217  ,  -52.54091   ],
       [  28.363104  ,  113.882706  ,   83.88499   ],
       [ -22.577091  ,    4.1770663 ,  -15.187515  ],
       [  94.97964   ,   10.708635  ,   -5.77984   ],
       [ -67.70693   ,   51.391525  , -171.72694   ],
       [ 130.33194   ,   -0.52616405,  -90.54762   ],
       [ -19.341948  ,   99.643364  , -171.6721    ],
       [  13.262712  ,  -15.923619  ,  -43.021008  ],
       [  14.614289  ,  -43.822548  ,    2.8250315 ],
       [  86.11116   ,  -41.090893  , -113.72276   ],
       [  78.16904   ,    3.1573396 , -104.395874  ],
       [  13.7859125 ,   -1.6231155 ,    5.8104167 ],
       [  98.63139   ,  -64.95606   ,  -34.36019   ],
       [   1.1491057 ,   43.33807   ,  -27.980244  ],
       [   6.9875207 ,   60.809807  ,  -69.08146   ],
       [  52.962624  ,  -12.712192  ,  -74.47648   ],
       [  76.47563   ,   74.634285  ,   86.33147   ],
       [   8.878473  ,   61.41717   ,   85.76429   ],
       [   3.8768647 ,   91.55854   ,   50.385612  ],
       [  28.638163  , -118.97644   ,  -58.817673  ],
       [ -24.903849  ,  -58.683083  ,  -86.88251   ],
       [ 114.642235  ,   45.131687  ,  -12.407091  ],
       [  55.72592   ,   -5.337019  ,  -30.32371   ],
       [  25.3512    ,   25.70854   ,  -54.944347  ],
       [ 140.69524   ,  -29.103662  ,  -68.22123   ],
       [ 105.15042   ,   70.7531    ,  -64.77917   ],
       [  62.332134  ,   99.05398   ,   34.090183  ],
       [  84.93102   ,   53.06872   ,   29.2672    ],
       [  47.71615   ,  -44.10332   ,  -51.825047  ],
       [  44.436535  ,   66.01078   ,   58.159805  ],
       [ -23.131027  ,   97.90149   ,   95.889244  ],
       [ -66.12919   ,   98.64582   , -147.86311   ],
       [  32.82587   ,   25.408045  ,   41.084957  ],
       [ 119.69434   ,  -35.527874  ,   57.76109   ],
       [  51.433064  ,  -18.897327  ,   15.844703  ],
       [  97.64787   ,   60.812687  ,  125.48791   ],
       [  35.11525   ,   64.712135  ,   15.03903   ],
       [  26.202007  ,   11.791995  , -171.14412   ],
       [ -26.546667  ,  -64.625755  , -131.92738   ],
       [-112.54296   ,   50.967594  ,  -50.53909   ],
       [  49.15238   ,   51.842575  , -138.58612   ],
       [ -30.446169  ,    0.90136814, -159.8395    ],
       [-110.911995  ,  130.96182   ,  -52.969482  ],
       [ 116.02406   ,   15.386539  ,   39.726803  ],
       [-114.71081   ,   93.1494    ,  -27.622816  ],
       [ -66.10404   ,   88.55825   ,  -14.26248   ],
       [-131.4128    ,   19.562502  ,  -91.585236  ],
       [ -29.800812  ,   75.8474    ,  -55.422894  ],
       [ -14.01907   , -181.0757    ,   78.01387   ],
       [ -66.65765   ,   50.93847   ,  -49.6698    ],
       [  45.91003   ,   17.250507  ,  158.0766    ],
       [ -71.56002   ,  -77.8242    , -127.43447   ],
       [ -77.839745  ,  -84.787704  ,  -74.078415  ],
       [ -56.456627  ,   63.741295  , -100.259476  ],
       [-113.92585   ,    0.69234383, -132.1958    ],
       [-127.36024   ,  114.45629   ,  -95.524155  ],
       [ -45.340828  ,  -49.38847   ,  -44.172672  ],
       [  66.08297   ,  -46.231544  ,  134.85986   ],
       [  71.57232   ,  109.981964  ,  -38.44788   ],
       [-147.85464   ,  103.55396   ,  -57.27206   ],
       [ -25.646309  ,  -15.720015  , -108.783775  ],
       [ 145.02179   ,  -77.858765  ,   -5.49723   ],
       [-138.52278   ,   18.10878   ,  -42.78388   ],
       [ -23.658041  ,  -10.83571   ,  -69.29861   ],
       [  10.006212  ,  -28.280416  ,  -83.67737   ],
       [  16.97242   ,   81.30034   , -129.06805   ],
       [ -89.90264   ,   85.773964  ,  -67.88139   ],
       [ 171.92845   ,   18.275452  ,   72.60772   ],
       [ -78.27276   ,  133.45631   ,  -89.19131   ],
       [ -67.317184  ,   18.771505  , -105.203926  ],
       [  10.478113  ,   11.942529  , -103.58848   ],
       [ -78.61757   ,   81.063995  ,   38.995193  ],
       [-136.76387   ,   67.653336  ,  -87.48154   ],
       [ -25.799685  ,  133.1542    ,  -38.21782   ],
       [ -17.776602  ,   61.00739   , -107.95447   ],
       [  73.17274   ,   27.444305  ,  -58.828365  ],
       [ -26.792645  ,  107.41751   ,  -89.91117   ],
       [ -15.48696   ,   40.98797   , -148.44879   ],
       [ -76.09988   ,    6.977534  ,  -43.05207   ],
       [  40.351315  ,  117.66717   ,  -72.50018   ],
       [-129.44388   ,   50.215965  ,   -5.0613146 ],
       [ -50.053997  ,  134.31119   ,    5.8494854 ],
       [ -75.053505  ,   32.320126  ,   -9.137705  ],
       [   9.962764  ,  -30.594828  , -131.33917   ],
       [ -32.62676   ,   35.417416  ,  -73.2697    ],
       [ -91.83463   ,  -38.775818  ,  -82.650955  ],
       [  24.600714  ,   95.56536   ,  -34.379974  ]], dtype=float32)